version: "3.3"
services:
  jersey-db:
    container_name: jersey-db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'register_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - exam-app-db:/var/lib/mysql
    ports:
      - '3307:3306'
    expose:
      - '3307'
  jersey-app:
    container_name: jersey-app
    restart: always
    build: .
    ports:
      - '8080:8080'
    volumes:
      - src:/opt/app/src
    depends_on:
      - jersey-db

volumes:
  exam-app-db:
  src: